title: Bladeswitch
description: The only starter compatible with BOTH Jekyll and Eleventy at the same time 🥷
styles:
  - https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css
  - https://cdn.jsdelivr.net/npm/@anydigital/breakout-css@0/src/breakout.min.css
header: |-
  Meet:
footer: |-
  Powered by [11ty](https://www.11ty.dev/)
  × [Jekyll](https://jekyllrb.com/)
  × [*Any*digital](https://any.digital/)
  © 2026
