title: Bladeswitch
description: The only starter compatible with BOTH Jekyll and Eleventy at the same time 🥷
styles:
  - https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css
header: |-
  Welcome to:
footer: |-
  Powered by [*Blade*switch](https://bladeswitch.com)
  × [*Any*digital](https://any.digital/)
  © 2026
