title: Bladeswitch
description: The only starter compatible with BOTH Jekyll and Eleventy at the same time 🥷
styles:
  - https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css
  - https://cdn.jsdelivr.net/npm/@anydigital/breakout-css@0/src/breakout.min.css
header: |-
  Meet:
footer: |-
  Powered by [11ty](https://github.com/11ty/eleventy)
  × [Jekyll](https://github.com/jekyll/jekyll)
  × [*Any*digital](https://any.digital/)
  © 2026

  [![GitHub Repo stars](https://img.shields.io/github/stars/anydigital/bladeswitch?logo=%20&label=🥷)](https://github.com/anydigital/bladeswitch)
